name: gestione_libri_server
description: A server app using the shelf package and Docker.
version: 0.5.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.2.0
  http: ^1.5.0
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  sqlite3: ^2.9.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.7.1
  lints: ^6.0.0
  shelf_router_generator: ^1.1.2
  test: ^1.26.2